### ISSUE TITLE
Hologram lighting

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#10]
Would it be possible to add a way to light up the holograms with some sort of light packet. This would make holograms easier to read in lower lit areas. You could even make this optional like `&g` maybe a `&h` or just general lighting?

**Comment by cyberpwnn** [comment]
I could send a chunk map packet which adds light to the surrounding air blocks. 

The only concern i have is this would have to be updated often (spigot randomly fixes lighting), but its worth a shot. Thanks for the idea!

**Comment by cyberpwnn** [comment]
Its lit fam 
![image](https://user-images.githubusercontent.com/10619135/47998275-bb973800-e0cc-11e8-8658-f59f19cb9619.png)
