### ISSUE TITLE
Chat Bubbles disable in certain worlds

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/Gloss#12]
The ability to disable chat bubbles in certain worlds.
Useful for if we have something like player duelling or a mob arena and we don't want chat bubbles to get in the way.

**Comment by cyberpwnn** [comment]
Great idea, thanks.

**Comment by DavidRockin** [comment]
Thanks for the suggestion, this has been implemented in 56fbe3a and will be deployed soon in GCB 1.2.
