### ISSUE TITLE
Hologram (gloss)

### ISSUE THREAD

**Issue by pompiere1** [VolmitSoftware/Gloss#13]
http://prntscr.com/l2pabb
if a player create an hologram near to you, your client crash
http://prntscr.com/l8220a
http://prntscr.com/l824a3
 i can't edit an hologram with book and quill

**Comment by cyberpwnn** [comment]
Perhaps its a colliding entity id? Ill try to reproduce. 

To edit a hologram, use /holo edit (while looking at it). You should get a book
Make your changes, but DONT SIGN AND CLOSE the book, just close the book.
Then use /holo edit (while holding the book AND while looking at the hologram)
The book should be removed and the changes to the hologram.

(i know the editing right now is shit, it needs work)

**Comment by cyberpwnn** [comment]
Fixed
