### ISSUE TITLE
Damage Indicators - Incompatability with changing weapon damage

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/Gloss#17]
My server uses the plugin OldCombatMechanics - which modifies the damage of weapons and tools to match that of what it used to be pre-1.9. Damage Indicators don't display the new damage values used by the weapons/tools and instead display the default 1.9 damage values.
![image](https://user-images.githubusercontent.com/24642838/52907432-9615ef00-32b5-11e9-929c-f8b5109d519d.png)
Pic related: The boss bar (from a different plugin) displays what the actual damage value is but Gloss's Damage Indicators display the incorrect vanilla value.

**Comment by TheWranger** [comment]
It also displays the wrong amount of damage when fighting against something with armor.

**Comment by cyberpwnn** [comment]
The damage indicators display the actual damage dealt to the target. 
1. Your plugin is probably cancelling the event and firing a "damage event" without an entity cause. If this is the case, gloss wont be able to tell who did the damage and therefore cant track it.
2. Armor calculation happens after gloss displays the damage, this can be fixed easily. Thanks!

**Comment by TheWranger** [comment]
Works properly now.
