### ISSUE TITLE
Tab header & footer

### ISSUE THREAD

**Issue by Curtis73** [VolmitSoftware/Gloss#19]
My server just crashed spontaneously, and I have no idea why, but after restarting it the header & footer now look like this:
![image](https://user-images.githubusercontent.com/14040165/52921017-b0c68300-330a-11e9-8913-7e7bf24b760b.png)
whilst my config still has it set to this:
![image](https://user-images.githubusercontent.com/14040165/52921030-c2a82600-330a-11e9-98cf-3286d3a2d177.png)

**Comment by cyberpwnn** [comment]
Interesting. It seems like gloss is saving the formatted text incorrectly and causing it to render improperly?

**Comment by cyberpwnn** [comment]
Cant seem to reproduce anymore

**Comment by Curtis73** [comment]
Thank you
