### ISSUE TITLE
Gloss Issues - Scoreboards, Console Errors, File Auto Updating

### ISSUE THREAD

**Issue by PerkusMaximus** [VolmitSoftware/Gloss#20]
```
MC Version: 1.12.2 / Latest Spigot Build
Gloss Version: 1.0.3
Plugins: PlaceholderAPI, ProtocolLib, Gloss, GlossDamageIndicators, React, GlossChatBubbles
```

Issue 1
-
When trying to create a header and footer RGB (&q) bar, the bottom one seems to only show up, while the top one doesn't (space in-between does though.) There's also a flicker every now and then, might be due to a glitchy thing of both bars. I added a space between them, and tried it with characters inside too, didn't make any difference except the characters show up on line 2 but the bar still doesn't show up above. I've also tried adding &r at the end of both, thought it might be an issue with that, didn't make a difference.
```json
{
    "permission": "default",
    "title": "&s&3&lGLOSS BOARD",
    "content": [
        "&q----------------------",
        " ",
        "&q----------------------"
    ],
    "primary": true
}
```
After some more testing, the issue with the header bar not showing up is it seems that two RGB bars won't work together, while a shiny header and a RGB footer will work together, but flicking still continues.
```json
{
    "permission": "default",
    "title": "&s&3&lGLOSS BOARD",
    "content": [
        "&s&8----------------------",
        " ",
        "&q----------------------"
    ],
    "primary": true
}
```
Issue 2
-
I'm probably missing something but hot dropping doesn't work on the latest gloss after editing and saving a file, constantly have to restart the server for it to update.

Issue 3
-
After shutting down the server, errors appear to follow.
[https://paste.volmit.com/igunubexeq.md](http://paste.volmit.com/igunubexeq.md)

**Comment by cyberpwnn** [comment]
Split your issues please. Ill do it this time. 

Too much in one issue prevents me from being able to do a small amount of work and close something
