### ISSUE TITLE
Holograms Sometimes Disappear

### ISSUE THREAD

**Issue by CraftSteamG** [VolmitSoftware/Gloss#27]
I am unsure how to report this, as I receive no console errors, but sometimes holograms disappear client-side, but a relog fixed this. I believe it has to do with chunk loading, because I can leave, run purge-chunks with React, then log in, and sometimes they will disappear, however, I could be wrong.

**Comment by cyberpwnn** [comment]
Perhaps its view distance?

**Comment by cyberpwnn** [comment]
Should be fixed with 1.0.8
