### ISSUE TITLE
OldCombatMechanics Hook

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/Gloss#28]
Since Gloss doesn't display the correct value with OldCombatMechanics, could we possibly get some sort of hook? A lot of servers will run oldcombatmechanics because of how it can bring back 1.8 combat to 1.9+ servers.
https://bstats.org/plugin/bukkit/OldCombatMechanics

**Comment by cyberpwnn** [comment]
No need, should just need to measure the health actually taken. Also #17
