### ISSUE TITLE
Error when moving holograms

### ISSUE THREAD

**Issue by Firefox8821** [VolmitSoftware/Gloss#31]
03.03 06:47:56 [Server] INFO RaimuTheFloofy issued server command: /holo move 03.03 06:47:56 [Server] ERROR null 03.03 06:47:56 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'holo' in plugin Gloss v1.0 03.03 06:47:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191] 03.03 06:47:56 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-551] 03.03 06:47:56 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 03.03 06:47:56 [Server] INFO Caused by: java.lang.NoSuchFieldError: BLOCK_ENDERCHEST_CLOSE 03.03 06:47:56 [Server] INFO at com.volmit.gloss.context.GlossDescriptor.pulse(GlossDescriptor.java:276) ~[?:?] 03.03 06:47:56 [Server] INFO at com.volmit.gloss.command.CommandMoveHologram.handle(CommandMoveHologram.java:84) ~[?:?] 03.03 06:47:56 [Server] INFO at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:85) ~[?:?] 03.03 06:47:56 [Server] INFO at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99) ~[?:?] 03.03 06:47:56 [Server] INFO at mortar.bukkit.plugin.MortarPlugin.onCommand(MortarPlugin.java:469) ~[?:?] 03.03 06:47:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-551]

**Comment by cyberpwnn** [comment]
Fixed
