### ISSUE TITLE
Hologram issues

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#32]
1) The edit book provides a shows formatted message making it hard to read stuff like &f text. It would be more useful to translate it into & format when the user gets/opens the book.

2) I am unable to have a blank page (blank line) on a hologram using the book.

3) The hologram doesn't autosave when edited to hologram file. (e.g. mine still says default hologram message)

4) &g doesn't show particles

`Gloss 1.0.13 and paperspigot 1.13.2 build 535`

**Comment by LogGits** [comment]
1) Somewhat fixed. It was working and now after i added a new line `&c&gTesting1234567` and closed the book, when i reopen or /gloss edit, it gives me the coloured book.

2) Fixed (<blank>) However, It would also be nice to have blank pages that auto fill `<blank>`

3) Fixed

**Comment by cyberpwnn** [comment]
1. I think the book is formatting itself or something weird. When gloss gives you a new book. We should be commenting on the split issues

2. Ill see what i can do. There is a lot of text filtering and trimming

3. Good

**Comment by cyberpwnn** [comment]
Fixed #34 and #35 again in 1.0.15

**Comment by cyberpwnn** [comment]
All fixed
