### ISSUE TITLE
Hologram irregularities

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#40]
I have started noticing some weird things happening to the holograms.
1) Randomly text vanishes from holograms (https://gyazo.com/18059c01e79502ed499bd1b9eb6f514e) `/gloss reload` doesn't fix it (haven't tested restarts). Second line of the creative hologram should say "Status: offline", and the first line of the other hologram is supposed to say `Survival`. There is one hologram with 5 lines now shows only 2.

2) Sometimes i see double text, a hologram will show 1 line twice in the same spot. (forgot to take a screenshot of this sorry)

3) chatbubbles also show doubled messages some times. (i am using chatcontrol pro but i suspect its related to gloss because non chat related things also have double text sometimes)

**Comment by cyberpwnn** [comment]
Was gloss reloaded via a plugin manager or something?
Also what server version?

**Comment by LogGits** [comment]
Reloaded via the gloss reload command and server version paperspigot 1.13.2 build 535

**Comment by cyberpwnn** [comment]
Make separate issues, its easier than 1, 2, 3 :P Ill split them this time too
