### ISSUE TITLE
Chat bubbles Hide own messages not working on 1.13

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#51]
I have `hide-own-messages: false` but i cant see my own chat bubble messages.

**Comment by cyberpwnn** [comment]
What version of gloss are you using?

**Comment by cyberpwnn** [comment]
Works on 1.12 fine. Are you using 1.13?

**Comment by LogGits** [comment]
1.0.17 i think. Using paper 1.13.2 build 535

**Comment by cyberpwnn** [comment]
Cannot reproduce. Works as it should on 1.8-1.13.
