### ISSUE TITLE
Error when creating Holograms

### ISSUE THREAD

**Issue by BlackGamer000** [VolmitSoftware/Gloss#53]
Hello. :) 
Basically this issue doesn't allow me to use the Holograms of Gloss with the 1.8.8. Below you will find more informations:

Server Type: Spigot
Server Version: 1.8.8
Client Version: 1.8.8
Java Version: 8 
Pastebin Error: https://pastebin.com/EbeMaEyM 
How to Reproduce: Create a 1.8.8 Server and join with the 1.8.8, if you type /hologram create the server will kick you and it will throw the error i sent above (Pastebin ^^) 

Thanks a lot and have a nice day :)

**Comment by cyberpwnn** [comment]
We have not run tests with 1.8 just yet :P see https://github.com/VolmitSoftware/Gloss#holograms

**Comment by BlackGamer000** [comment]
Okay c: 
If it works i notify on Discord or on GitHub?

**Comment by cyberpwnn** [comment]
Support for 1.8 added in 1.0.18
