### ISSUE TITLE
Board Issues + Errors

### ISSUE THREAD

**Issue by BlackGamer000** [VolmitSoftware/Gloss#55]
Another issue detected with the 1.8.8. 

https://pastebin.com/9YyWuPrk

**Comment by cyberpwnn** [comment]
Requires some additional investigation. Boards seemed to work fine for me. Do you have the board config (in plugins/gloss/boards) you used? perhaps it was text length that caused it. @Puretie

**Comment by BlackGamer000** [comment]
Yeah, i edited it and saved but after i reload it doesn't work. Yeah, the error is related to text length, i thought i can use it :c

**Comment by cyberpwnn** [comment]
Fixed in 1.0.18
