### ISSUE TITLE
Error on enabling Gloss (1.12.2)

### ISSUE THREAD

**Issue by FoviOX** [VolmitSoftware/Gloss#72]
Appearing error when Gloss enabling
**Spigot**: 1.12.2
**Gloss**: 1.0.29
**Mortar**: 1.0.65
Error from log: https://pastebin.com/03L2Vs8t
Full loading log: [latest.log](https://github.com/VolmitSoftware/Gloss/files/3276753/latest.log)
![image](https://user-images.githubusercontent.com/33469628/59277252-86595680-8c68-11e9-89cb-7c80a2f20f19.png)

**Comment by notpaz** [comment]
same on 1.8

**Comment by DavidRockin** [comment]
Hi, thanks for the report. This was fixed in 1.300, hoping to release within the next 48 hours. Cheers.
