### ISSUE TITLE
Reloading deletes lines of holograms

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#80]
For some reason after many reloads holograms start to lose some of the texts. e.g.
```
test
hello
hello
tester
123456789
```
would turn into:
```
test


tester

```
I noticed this when using /gloss reload trying to perfect the scoreboard. I looked at the hologram and it had blank rows.
on 1.13.2 paper build 639 using gloss 1.3.0 and mortar 1.0.70

**Comment by DavidRockin** [comment]
Can you paste the exact hologram configuration you're using.
