### ISSUE TITLE
Add option to escape colour/formatting codes

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/Gloss#82]
Sorry to ignore the Feature request template but it's clearly more for suggesting improvements rather than asking for actual features to be added.

My idea is to add a way to escape colour and formatting codes in holograms and similar to just show the text.
A small example:
I have the text `Use "&[colour]&s" to add a shine effect to your message.` set in the hologram. Now instead of formatting it to have the text after &s contain the shine effect, it would stay the same and just show it as I wrote it (maybe with using a \ before the &?)

**Comment by DavidRockin** [comment]
Gloss 1.3.1 implements a method to escape ampersands with a `\` Because of JSON formatting, you'll need to escape the slash, so you'll need to use `\\&` when editing the JSON files. Editing in-game you can escape ampersands with `\&`
