### ISSUE TITLE
"[Gloss]: Look at a hologram to edit it." message when Shift left/rightclick

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/Gloss#85]
**Describe the bug**
When you press shift (crouch) and either left or rightclick (Rightclick has to be on something like an itemframe) does Gloss send the message `[Gloss]: Look at a hologram to edit it.`

**To Reproduce**
1. Crouch.
2. Leftclick a block or rightclick something like an itemframe.

**Expected behavior**
Gloss shouldn't react to this action.

**Screenshots or Video Recordings**
![](https://thumbs.gfycat.com/FelineAnyCottontail-small.gif)

**Server and Plugin Informations**
- Installed plugins:
  - AdvancedCustomItemAPI
  - AdvancedCustomMenu
  - AdvancedModreq
  - Animatronics*
  - ArmorStandTools
  - BannerBoard*
  - BKCommonLib
  - DeluxeChat
  - DeluxePlugins*
  - DiscordSRV
  - Essentials
  - EssentialsSpawn
  - Gloss*
  - HeadDatabase*
  - HelpPagePlus
  - InfoHeads
  - ItemsAdder
  - LightAPI*
  - LuckPerms
  - Maplands
  - MessageAnnouncer
  - MiniaturePets*
  - Mortar*
  - PlaceholderAPI*
  - ProtocolLib*
  - QuickShop
  - ReWorld
  - ServerListPlus
  - SurveyPlus*
  - Vault
  - WarpSystem
  - WorldEdit
  - WorldGuard
- Gloss and Mortar Version:
  - Gloss: 1.3.1
  - Mortar: 1.0.71
- Server Platform and Version [eg: PaperSpigot 1.14.4]:
  - PaperMC 152 (1.14.4)
- Operating System (if applicable):
  - Not available

**Additional context**
There are no errors in console.

**Comment by Andre601** [comment]
Smaller update:
This happens every time you shift-Rightclick any kind of entity (e.g. armor stands)

**Comment by DavidRockin** [comment]
Thanks for the informative bug report. This issue has been fixed in 1.3.2. I've also made an alteration to prevent clicking on the same gloss displays, thus fixing duplicate books.
