### ISSUE TITLE
EventExeption

### ISSUE THREAD

**Issue by FoviOX** [VolmitSoftware/Gloss#88]
**Describe the bug**
Appearing error. I don't understand why.

**Screenshots or Video Recordings**
None.

**Server and Plugin Informations**
- Gloss 1.3.2
- Mortar 1.0.71
- Spigot 1.12.1
- Gloss addons: Not installed
- Plugin list:
![Screenshot_44](https://user-images.githubusercontent.com/33469628/63428571-81f7a980-c420-11e9-8222-588496283912.jpg)
![Screenshot_45](https://user-images.githubusercontent.com/33469628/63428573-8328d680-c420-11e9-8e66-64b3532ee0e5.jpg)
![Screenshot_46](https://user-images.githubusercontent.com/33469628/63428578-8623c700-c420-11e9-8cfb-7e517d6f0cb6.jpg)
![Screenshot_47](https://user-images.githubusercontent.com/33469628/63428581-87ed8a80-c420-11e9-8186-8e07bab12f0a.jpg)

**Additional context**
https://pastebin.com/h8iHC93u

**Comment by DavidRockin** [comment]
Please use the bug report template.

**Comment by FoviOX** [comment]
Edited issue.

**Comment by DavidRockin** [comment]
Thanks for the report. This is fixed in 1.3.3, caused when a player is looking at a hologram and interacts with redstone blocks.
